language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy
install:
  - pip install tox-travis coveralls
script: tox
after_success:
  - coverage combine
  - coveralls
cache:
  pip: true
notifications:
  webhooks:
    secure: 2BDTBfD49EsQcdRHeimlmhvLadc7A42ba9Xw4ioPYtAfu0iyAuD64b/J+y5iyssyKUt47Yg9dFDjY0Fxb/jPxq+P+qEF7e9hRWRBxL6lUlJRmobV0XD1zkjTnuLa76wj04qQVfFwwXEF2qdUq5cTspJdH3uG7/L4rviDxLuDsJ87W/Fw1/r+P1zIOY31KC7E5bB5dpKlEI5wLTNmesk29AhlqMgEyE20/b0pa05gWmzgjzcugnw5e/Rja4s5IKzz9Q0kw3Cf2J1qZcWX8Ul16lQf2hUR0578yMNs0iVqI+CBusVQ4c1pPs3mdnFXm7KaN6vqfyRsBUScETVyy1m7m3wmlRzR0YER14whUq9VL/70jY6SXlg01oThuz2kGKeU3SUMBsq+YrNCMXX76PUVUPjoKLTsLGW+IjOlQsdi6jLKkIqNXdLO2sMx5tNGwPDf/N9MyARbYvEwTFC9xDpi6kLSCKGIcqIjruKcj8R0anbA9dS8V+okvOtW2iNfLTecli9zm6CQ8F8cx6fxDqz89giqdFtjsnnQRXG1f7/o4uVKsJQ04PjrYuoXFmvGwBpCz/ghgF1gaLfKHQMuJf6U3on0DVMXo1bu3KpCknNwJ2GFB6iDUAjxQH7Jy0paG5FfsnnTLpmJuU67n4aSIMOyjrCxQEMzK0svqoIln1MYzHE=
